<?php
	define("TITULO", "CADASTRO DE FUNCIONARIOS");
	include "cabecalho.php";
	include_once "connect/connect.php";
	include "funcoes.php";
	if(!isset($_GET['cad'])){	
		echo '<div class="jumbotron jumbotron-fluid">';
		echo '<marquee class="marquee"><h3>CADASTRO DE FUNCIONARIOS</h3></marquee>';
		echo '</div>';
		echo '<div class="img col-sm-12">';
		echo '<div class="container">';
			echo '<div class="row ">';
				echo '<div class="col-sm-6">';
					echo '<form action="" method="get" enctype="multipart/form-data">';
					echo '<div class="form-group">';
					echo '<label for="nome">';
					echo '<strong>Nome:</strong>'; 
					echo '</label>';
					echo '<input id="nome" class="form-control inp" type="text" name="nome" autocomplete="off" required>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label for="sobrenome">';
					echo '<strong>Sobrenome:</strong>';
					echo '</label>';
					echo '<input id="sobrenome" class="form-control inp" type="text" name="sobrenome" autocomplete="off" required>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label>';
					echo '<strong>Telefone:</strong> <input class="form-control inp" type="text" name="telefone1" autocomplete="off" required>';
					echo '</label>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label>';
					echo '<strong>Telefone (opcional): </strong><input class="form-control inp" type="text" name="telefone2" autocomplete="off">';
					echo '</label>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label for="email">';
					echo '<strong>Email:</strong>';
					echo '</label>';
					echo '<input id="email" class="form-control inp" type="email" name="email" autocomplete="off" required>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label for="log">';
					echo '<strong>Logradouro:</strong>';
					echo '</label>';
					echo '<input id="log" class="form-control inp" type="text" name="logradouro" autocomplete="off" required>';
					echo '</div>';
				echo '</div>';
				echo '<div class="col-sm-6">';
					echo '<div class="form-group">';
					echo '<label for="bairro">';
					echo '<strong>Bairro:</strong>';
					echo '</label>';
					echo '<input id="bairro" class="form-control inp" type="text" name="bairro" autocomplete="off" required>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label>';
					echo '<strong>Nº: </strong><input class="form-control inp" type="text" name="numero" autocomplete="off" required>';
					echo '</label>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label>';
					echo '<strong>CEP: </strong><input class="form-control inp" type="text" name="cep" autocomplete="off" required>';
					echo '</label>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label>';
					echo '<strong>ID Categoria: </strong><input class="form-control inp" type="text" name="categoria" autocomplete="off" required>';
					echo '</label>';
					echo '</div>';
					echo '<div class="form-group">';
					echo '<label>';
					echo '<strong>ID Departamento: </strong><input class="form-control inp" type="text" name="departamento" autocomplete="off" required>';
					echo '</label>';
					echo '</div>';
					echo '<input type="submit" class="btn btn-primary" value="Cadastrar" name="cad">';
					echo '<a href="inicial.php"><input type="button" value="HOME" class="btn btn-danger"></a><br>';
				echo '</div>';
				echo '</form>';
			echo '</div>';
			echo '</div>';
	}else{
		$nome = $_GET['nome'];
		$sobrenome = $_GET['sobrenome'];
		$telefone1 = $_GET['telefone1'];
		$telefone2 = $_GET['telefone2'];
		$email = $_GET['email'];
		$logradouro = $_GET['logradouro'];
		$bairro = $_GET['bairro'];
		$numero = $_GET['numero'];
		$cep = $_GET['cep'];
		$categoria = $_GET['categoria'];
		$departamento = $_GET['departamento'];

		$cadastro = cadastrarFuncionario($connect, $nome, $sobrenome, $telefone1, $telefone2, $email, $logradouro, $bairro, $numero, $cep, $categoria, $departamento);
		header("Location:sucesso.php?sucesso");
		}
	include "rodape.php";
?>